id: P03686830
initial_creation_type: input
source_metadata:
  title: Dīrghāgama, sūtras no. 35-41
  language: sa
  volumes:
    c71967a9b4cc4224b5d9d3b2b0c0f69c:
      title: Complete text
      base_file: Complete text.txt
      work_id: W7C824283
  chapter_to_tile: {}
created_at: '2022-03-02T08:53:54.437375'
last_modified_at: '2022-03-02T08:53:54.437386'
